[package]
name = "rls"
version = "0.122.0"
authors = ["Nick Cameron <ncameron@mozilla.com>", "Jonathan Turner <jturner@mozilla.com>", "The RLS developers"]
description = "Rust Language Server - provides information about Rust programs to IDEs and other tools"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang-nursery/rls"
categories = ["development-tools"]

build = "build.rs"

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo" }
env_logger = "0.4"
jsonrpc-core = "7.0.1"
languageserver-types = "0.12"
lazy_static = "0.2"
log = "0.3"
racer = "2.0.6"
rls-analysis = { git = "https://github.com/Xanewok/rls-analysis", branch = "multi-crates" }
rls-data = { version = "0.12", features = ["serialize-serde"] }
rls-rustc = "0.1"
rls-span = { version = "0.4", features = ["serialize-serde"] }
rls-vfs = { version = "0.4", features = ["racer-impls"] }
rustfmt-nightly = "0.2.13"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.1.0"
